### ISSUE TITLE
Iframe does not load

### ISSUE THREAD

**Issue by SkymanOne** [gregberge/error-overlay-webpack-plugin#75]
I get an error when using webpack 5 with this plugin.

The chrome error console says:
`Error: Iframe has not been created yet.`

**Comment by gregberge** [comment]
Fixed in v1.0.0.

**Comment by SkymanOne** [comment]
> Fixed in v1.0.0.

the problem still persists.
When error occurs, no logs are displayed and console still says `Error: Iframe has not been created yet.
![](https://i.imgur.com/Bk311FE.png)

The chrome shows the same thing.

I am using custom setup with web pack, HtmlWebpackLoader and webpack-dev-server

**Comment by CptnFizzbin** [comment]
this was closed as completed, but v1.1.1 still has this issue.
